// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqqktfxojtmizwtbiuqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xcWt0ZnhvanRtaXp3dGJpdXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODk1MTYsImV4cCI6MjA2NDc2NTUxNn0.dxI-TlNtXTmuqzFgv5PH-zBJz0JcxbPo1agoA6HGm14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);